name: Server tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2

            - name: Use Node.js 20.x for Server Side
              uses: actions/setup-node@v2
              with:
                  node-version: 20.x

            - name: Installing dependencies
              run: npm install
              working-directory: ./server

            - name: Run tests
              working-directory: ./server
              run: npm test
